#!/usr/bin/env python
"""trigger bulk import

 ./complex_object_bulk_importer --indir /apps/content/new_path/UCI/UCIHistoryPublications/complex/ --project UCIHistoryPublications --campus UCI --leafType CustomFile --folderishType CustomFile

"""
import sys
import argparse
import os
from pynux import utils

def main(argv=None):
    """main"""
    parser = argparse.ArgumentParser()

    parser.add_argument('--indir', required=True)
    parser.add_argument('--campus', required=True)
    parser.add_argument('--project', required=True)
    parser.add_argument('--leafType', required=True)
    parser.add_argument('--folderishType', required=True)

    if argv is None:
        argv = parser.parse_args()

    nx = utils.Nuxeo({
        "user": os.environ.get('NUXEO_API_USER', 'Administrator'),
        "password": os.environ.get('NUXEO_API_PASS', 'Administrator')
    })

    #print call_api(api_base, api_auth, "logActivate", {})
    #print call_api(api_base, api_auth, "log", {})
    for document in get_immediate_subdirectories(argv.indir):
        input_path = os.path.join(argv.indir, document)
        target_path = os.path.join("asset-library", argv.campus, argv.project)
        nx.import_one_folder(argv.leafType, input_path, target_path, argv.folderishType )
    
# api_get "logActivate"
# api_get "status"
# api_get "run?leafType=$leafType&inputPath=/apps/content/new_path/$campus/$collection&targetPath=asset-library/$campus&folderishType=Organization"
# api_get "log"

def get_immediate_subdirectories(dir):
    """ et all of the immediate subdirectories in python http://stackoverflow.com/a/800201/1763984 """
    return [name for name in os.listdir(dir)
            if os.path.isdir(os.path.join(dir, name))]

# main() idiom for importing into REPL for debugging
if __name__ == "__main__":
    sys.exit(main())
