#!/usr/bin/env python

import sys
from pprint import pprint as pp
pp(sys.path)
import argparse
import os
import requests
import json
import shutil
from pynux import utils

def main(argv=None):


    parser = argparse.ArgumentParser( description='nuxeo metadata via REST API')
    if argv is None:
        argv = parser.parse_args()

    # http://demo.nuxeo.com/nuxeo/api/v1/path/default-domain/@search\?query\=SELECT%20\*%20FROM%20Document\&pageSize\=2\&currentPageIndex\=1 | jq .
    # todo; add these defaults as parameters as well as env
    api_base = os.environ.get('NUXEO_REST_API', "http://localhost:8080/nuxeo/site/api/v1")
    api_auth = ( os.environ.get('NUXEO_API_USER', "Administrator"), 
                 os.environ.get('NUXEO_API_PASS', "Administrator") )
    nx = utils.Nuxeo()
    documents = nx.all()
    print_document_summary(documents)

def print_document_summary(documents):
    for document in documents:
        print "{0}\t{1}".format(document['path'], document['uid'])

# main() idiom for importing into REPL for debugging 
if __name__ == "__main__":
    sys.exit(main())
