#!/usr/bin/env python

import sys
import argparse
from pynux import utils
import pprint


def main(argv=None):
    parser = argparse.ArgumentParser(description='nxql via REST API')
    parser.add_argument('nxql', nargs=1, help="nxql query")
    if argv is None:
        argv = parser.parse_args()

    nx = utils.Nuxeo()
    pprint.pprint(argv.nxql[0])
    documents = nx.nxql(argv.nxql[0])
    nx.print_document_summary(documents)


# main() idiom for importing into REPL for debugging
if __name__ == "__main__":
    sys.exit(main())
